config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'signup', to: 'users#new'
  resources :users, except: [ :new ]
  get 'login', to: 'session#new'
  get 'wanderer', to: 'chatbot#index'
  post 'login', to: 'sessions#create'
  delete "logout", to: "sessions#destroy"
  post "message", to: 'messages#create'
  get 'locations', to: 'locations#index'
  get 'locations/:id', to: 'locations#show'
end

app/views/layouts/_location_card.html.erb
<div class="centered column">
  <div class="ui card" id="location-card">
    <div class="content">
      <div class="center aligned header"><%=link_to object.hotel_name, "/locations/#{object.id}"%></div>
      <div class="center alignedmeta"><%= "#{object.geodata[:city]}, #{object.geodata[:country]}, #{object.geodata[:continent]}"%></div>
    </div>
    <div class="content">
      <div class="description">
      </div>
    </div>
    <div class="center aligned extra content">
      <%object.star_rating.times do %>
        <i class="star icon"></i>
      <%end%>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<%=link_to "//FIRST HOLIDAYS", root_path, class:"item", id:"title_header" %>
<div class="right menu">
  <div class="right menu">
    <%=link_to "Wanderer", '/wanderer', class:"item" %>
    <%=link_to "Locations", '/locations', class:"item" %>
    <% if logged_in?%>
      <div class="item">Logged in as <%= current_user.first_name %></div>
      <%= link_to "Log out", logout_path, method: :delete, class:"item"%>
    <%else%>
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <%= form_with(scope: :session, url: login_path, class: "ui form", role:"form", local: true, id: "login-form") do |f|%>
            <div class="field">
              <%= f.label :email, "Email"%>
              <%= f.email_field :email, placeholder: "Email"%>
            </div>
            <div class="field">
              <%= f.label :password, "Password"%>
              <%= f.password_field :password, placeholder:"Password"%>
            </div>
            <div class="field">
              <div class="ui checkbox">
                <input type="checkbox" tabindex="0" class="hidden">
                <label>Remember me</label>
              </div>
            </div>
            <%= f.submit "Login", class: "ui submit button fluid"%>
          <%end%>
          <div class="ui horizontal divider"id="divider"> Or </div>
          <%= link_to "Sign up", signup_path, class:"centere aligned link item", id:"sign-up"%>
        </div>
      </div>
    <%end%>
    <div class="item"><i class="search icon"></i></div>
  </div>
</div>

app/views/layouts/_statusmessages.html.erb
<% flash.each do |message_type, message_content|%>
  <div class="ui <%=message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%=message_content%>
    </div>
  </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstHolidayChatAgent</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script>
      const conversation_id = <%=current_conversation.id or 1%>
    </script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&family=Unbounded:wght@200;300;400;500&display=swap" rel="stylesheet">
  </head>
  <body>
    <div class="ui inverted menu large" id="nav-bar">
      <%= render 'layouts/navigation' %>
    </div>
    <div class="ui container"style="margin-top: 2rem;">
      <%= render 'layouts/statusmessages'%>
      <%= yield %>
    </div>
  </body>
</html>